### ISSUE TITLE
Idea - Task Result Binders overload

### ISSUE THREAD

**Issue by jvasmotta** [salvois/DiscriminatedOnions#1]
Hi @salvois,

Beautiful code.
According to you would be valid, of is there a value by adding a Task Result Binder overload to Result record?

`        public static Task<Result<U, TError>> Bind<T, TError, U>(this Result<T, TError> result, Func<T, Task<Result<U, TError>>> binder) =>
            result.Match(error => Task.FromResult(Error<U, TError>(error)), binder);`
            
This other overload would be also necessary:

`        public Task<U> Match<U>(Func<TError, Task<U>> onError, Func<T, Task<U>> onOk) =>
            this switch
            {
                Error error => onError(error.ErrorValue),
                Ok  ok => onOk(ok.ResultValue),
                _ => throw new ArgumentOutOfRangeException()
            };`

Kind regards,
Jo

**Comment by salvois** [comment]
Hi @jvasmotta , fortunately we could discuss this in person :) Please feel free to experiment and open a pull request with your proposal. Examples welcome. Many thanks!

**Comment by salvois** [comment]
Hi @jvasmotta , I have finally added async versions of the bind, iter and map functions for the Option and Result types in release 1.2. Please have a look and tell me if that makes sense for you, if you are still interested ;)
Thanks,
   Salvo
